name: Keep Streamlit App Alive

on:
  schedule:
    - cron: "*/50 * * * *"   # every 50 minutes
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Streamlit app
        run: curl -s https://bengaluru-housepriceprediction.streamlit.app/ > /dev/null
